/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-fhss_utils
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#ifndef INCLUDED_FHSS_UTILS_API_H
#define INCLUDED_FHSS_UTILS_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_fhss_utils_EXPORTS
#define FHSS_UTILS_API __GR_ATTR_EXPORT
#else
#define FHSS_UTILS_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_FHSS_UTILS_API_H */
