/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tagged_burst_to_pdu.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1980177101ed46f9da7357bf412c1898)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/fhss_utils/tagged_burst_to_pdu.h>
// pydoc.h is automatically generated in the build directory
#include <tagged_burst_to_pdu_pydoc.h>

void bind_tagged_burst_to_pdu(py::module& m)
{

    using tagged_burst_to_pdu = ::gr::fhss_utils::tagged_burst_to_pdu;


    py::class_<tagged_burst_to_pdu,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<tagged_burst_to_pdu>>(
        m, "tagged_burst_to_pdu", D(tagged_burst_to_pdu))

        .def(py::init(&tagged_burst_to_pdu::make),
             py::arg("decimation"),
             py::arg("taps"),
             py::arg("min_burst_time"),
             py::arg("max_burst_time"),
             py::arg("relative_center_frequency"),
             py::arg("relative_span"),
             py::arg("relative_sample_rate"),
             py::arg("sample_rate"),
             py::arg("num_threads"),
             D(tagged_burst_to_pdu, make))


        ;
}
